version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5435:5435"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8082"